name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Check Formatting
        run: nix fmt -- --check .

  build:
    strategy:
      matrix:
        platform:
          - x86_64-darwin
          - aarch64-darwin
        include:
          - platform: x86_64-darwin
            runner: macos-13  # this is the latest intel runner
          - platform: aarch64-darwin
            runner: macos-latest
    runs-on: ${{ matrix.runner }}  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    - name: Cache Nix
      uses: DeterminateSystems/magic-nix-cache-action@v3
    - name: Backup config files
      run: |
        sudo mv /etc/nix/nix.conf{,.before-nix-darwin}
        sudo mv /etc/shells{,.before-nix-darwin}
        sudo mv /etc/zshenv{,.before-nix-darwin}
    - name: Switch to nix-darwin ci env
      run: |
        nix --extra-experimental-features 'nix-command flakes' \
          run nix-darwin -- switch --flake .#ci-${{ matrix.platform }}
      env:
        NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
